config/routes.rb
Weblog::Application.routes.draw do
  scope module: :web do
    resources :posts do
      scope module: :posts do
        resources :comments, only: [:new, :create, :destroy]
      end
    end
    root 'welcome#index'
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy

  mount_uploader :picture, PictureUploader

  state_machine :state, initial: :unpublished do
    state :published
    state :unpublished

    event :publish do
      transition [:unpublished] => :published
    end
    event :unpublish do
      transition [:published] => :unpublished
    end
  end

  include PostRepository
end

app/models/post/comment.rb
class Post::Comment < ActiveRecord::Base
  belongs_to :post
  has_ancestry
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_breadcrumb :index, :root_path
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  add_breadcrumb :index, :posts_path

  http_basic_authenticate_with name: "dhhh", password: "secret", except: [:index, :show]

  def new
    @post = PostEditType.new
  end

  def create
    # render text: params[:post].inspect
    @post = PostEditType.new(params[:post])
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = resource_post
    add_breadcrumb @post.title, post_path(@post)
  end

  def index
    @posts = Post.all #FIXME use Post.web
  end

  def edit
    @post = resource_post
    add_breadcrumb @post.title, post_path(@post)
  end

  def update
    @post = PostEditType.find(params[:id])
    # raise params.inspect
    if @post.update(params[:post])
      redirect_to @post
    else
      # p @post.errors
      render 'edit'
    end
  end

  def destroy
    @post = resource_post
    @post.destroy

    redirect_to posts_path
  end

  def resource_post
    Post.find(params[:id])
  end

end

app/controllers/web/application_controller.rb
class Web::ApplicationController < ApplicationController

  private
  def resource_post
    Post.find(params[:id])
  end

end

app/controllers/web/posts/application_controller.rb
class Web::Posts::ApplicationController < Web::ApplicationController
  private
  def resource_post
    Post.web.find(params[:post_id])
  end
end

app/controllers/web/posts/comments_controller.rb
class Web::Posts::CommentsController < Web::Posts::ApplicationController

  add_breadcrumb :index, :post_comments_path
  http_basic_authenticate_with name: "dhhh", password: "secret", only: :destroy

  def new
    @post = resource_post
    @comment = CommentEditType.new(params.extract(:parent_id))
  end

  def create
    comment = CommentEditType.new(params[:post_comment])
    comment.post = resource_post
    comment.save
    redirect_to post_path(resource_post)
  end
  def destroy
    @comment = resource_post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(resource_post)
  end

end

app/controllers/web/posts_controller.rb
class Web::PostsController < Web::ApplicationController
  add_breadcrumb :index, :posts_path

  http_basic_authenticate_with name: "dhhh", password: "secret", except: [:index, :show]

  def new
    @post = PostEditType.new
  end

  def create
    # render text: params[:post].inspect
    @post = PostEditType.new(params[:post])
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = resource_post
    @comment = CommentEditType.new()
    add_breadcrumb @post.title, post_path(@post)
  end

  def index
    query = { s: 'created_at desc' }.merge(params[:q] || {})
    @q = Post.ransack(query) #FIXME use Post.web.ransack(query)
    @posts = @q.result.page(params[:page]).decorate
  end

  def edit
    @post = resource_post
    add_breadcrumb @post.title, post_path(@post)
  end

  def update
    @post = PostEditType.find(params[:id])
    # raise params.inspect
    if @post.update(params[:post])
      redirect_to @post
    else
      # p @post.errors
      render 'edit'
    end
  end

  def destroy
    @post = resource_post
    @post.destroy

    redirect_to posts_path
  end

  private
  def resource_post
    Post.find(params[:id])
  end

end

app/controllers/web/welcome_controller.rb
class Web::WelcomeController < Web::ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/web/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Weblog"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="/") Weblog
          .container.nav-collapse
            %ul.nav
              / %li= link_to "Link 1", "/path1"
              / %li= link_to "Link 2", "/path2"
              / %li= link_to "Link 3", "/path3"

    .container-fluid

      .row-fluid
        / .span3
        /   .well.sidebar-nav
        /     %ul.nav.nav-list
        /       %li.nav-header Sidebar
        /       %li= link_to "Link 1", "/path1"
        /       %li= link_to "Link 2", "/path2"
        /       %li= link_to "Link 3", "/path3"
        .span12
          = render_breadcrumbs
          = bootstrap_flash
          = yield

      %footer
        %p &copy; Company 2013

app/views/web/posts/_form.html.haml
= simple_form_for @post, html: { class: 'form-horizontal' } do |f|
  = f.input :state_event, as: :state_event
  = f.input :picture, as: :image_preview
  = f.input :picture_cache, as: :hidden
  = f.input :title
  = f.input :text

  .form-actions
    = f.button :submit, class: 'btn'
    = link_to t('.cancel'), posts_path, class: 'btn'

app/views/web/posts/comments/_comment.html.haml
- if @post.comments.any?
  %table.table.table-striped
    %thead
      %tr
        %th= :id
        %th= :commenter #model_class.human_attribute_name(:commenter)
        %th= :body #model_class.human_attribute_name(:body)
        %th= :created_at #model_class.human_attribute_name(:created_at)
        %th= :parent_id
        %th=t '.actions'
    %tbody
      - @post.comments.each do |comment|
        %tr
          %td= comment.id
          %td= comment.commenter
          %td= comment.body
          %td=l comment.created_at, format: :short
          %td= comment.parent_id
          %td
            = link_to t('.destroy'), post_comment_path(@post, comment), method: :delete, data:  { confirm:  t('.confirm') }, class: 'btn btn-mini btn-danger'
            = link_to t('.reply'), new_post_comment_path(@post, parent_id: comment), class: 'btn btn-mini'
- else
  %p no comments

app/views/web/posts/comments/_form.html.haml
= simple_form_for(@comment, url: post_comments_path(@post), html: { class: 'form-horizontal' }) do |f|
  = f.input :commenter
  = f.input :body
  = f.input :parent_id, as: :hidden

  .form-actions
    = f.button :submit, class: 'btn-primary'

app/views/web/posts/comments/new.html.haml
- model_class = Post::Comment
.page-header
  %h1=t 'helpers.titles.new', model: model_class.model_name.human.titleize
= render partial: "web/posts/comments/form"

app/views/web/posts/edit.html.haml
- model_class = Post
.page-header
  %h1=t 'helpers.titles.edit', model: model_class.model_name.human.titleize
= render partial: "form"

app/views/web/posts/index.html.haml
- model_class = Post
.page-header
  %h1=t '.title', default: model_class.model_name.human.pluralize.titleize

= paginate @posts

%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:state)
      %th= model_class.human_attribute_name(:picture)
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:text)
      %th= model_class.human_attribute_name(:created_at)
      %th=t ('.comments')
      %th=t ('.actions')
  %tbody
    - @posts.each do |post|
      %tr
        %td= link_to post.id, post_path(post)
        %td= post.human_state_name
        %td
          - if post.picture?
            .thumbnail
              = image_tag post.picture.thumb
        %td= post.title
        %td= post.text
        %td= l post.created_at, format: :short
        %td= post.comments_count
        %td
          = link_to t('.edit'), edit_post_path(post), class: 'btn btn-mini'
          = link_to t('.destroy'), post_path(post), method: :delete, data: { confirm: t('.confirm') }, class: 'btn btn-mini btn-danger'

= paginate @posts

= link_to t('.new'), new_post_path, class: 'btn btn-primary'

app/views/web/posts/new.html.haml
- model_class = Post
.page-header
  %h1=t 'helpers.titles.new', model: model_class.model_name.human.titleize
= render partial: "form"

app/views/web/posts/show.html.haml
- model_class = Post
.page-header
  %h1=t '.title', default: model_class.model_name.human.titleize

= image_tag @post.picture
%p
  %strong= model_class.human_attribute_name(:title) + ':'
  %br
  = @post.title
%p
  %strong= model_class.human_attribute_name(:text) + ':'
  %br
  = @post.text

%h2 Comments
/ = render @post.comments
= render "web/posts/comments/comment"

- if @post.published?
  %h2 Add a comment:
  = render "web/posts/comments/form"

.form-actions
  = link_to t('.back'), posts_path, class: 'btn'
  = link_to t('.edit'), edit_post_path(@post), class: 'btn'
  = link_to t('.destroy',), post_path(@post), method: "delete", data: { confirm: t('.confirm') }, class: 'btn btn-danger'

app/views/web/welcome/index.html.haml
%h1 Hello, Rails!
= link_to "My Blog", controller: "posts"